# Generated by Django 4.2.7 on 2025-10-13 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dni_checker', '0002_webauthncredential'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dni', models.CharField(db_column='id_usuario', max_length=16)),
                ('partido', models.CharField(db_column='id_eleccion', max_length=100)),
                ('nombre', models.CharField(db_column='id_candidato', max_length=100)),
                ('ts', models.BigIntegerField(db_column='fecha_voto')),
            ],
            options={
                'db_table': 'votos',
                'managed': False,
            },
        ),
    ]
