# Generated by Django 4.2.7 on 2025-10-14 01:38

from django.db import migrations, models
import dni_checker.models


class Migration(migrations.Migration):

    dependencies = [
        ('dni_checker', '0003_voto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=16, unique=True)),
                ('nombres', models.CharField(max_length=255)),
                ('apellido_paterno', models.CharField(max_length=255)),
                ('apellido_materno', models.CharField(max_length=255)),
                ('nombre_completo', models.CharField(max_length=512)),
                ('genero', models.CharField(blank=True, max_length=2)),
                ('fecha_nacimiento', models.CharField(blank=True, max_length=32)),
                ('codigo_verificacion', models.CharField(blank=True, max_length=8)),
                ('distrito', models.CharField(blank=True, max_length=255)),
                ('raw_json', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(db_index=True, max_length=16)),
                ('phone', models.CharField(max_length=32)),
                ('otp', models.CharField(max_length=8)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            # The column already exists in the database; we only need Django's state to include it.
            state_operations=[
                migrations.AddField(
                    model_name='dnitoken',
                    name='expires_at',
                    field=models.DateTimeField(default=dni_checker.models._expires_default),
                ),
            ],
            database_operations=[
                # No-op to avoid trying to add a column that already exists
            ],
        ),
        migrations.CreateModel(
            name='VotoDistrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=16)),
                ('distrito', models.CharField(max_length=255)),
                ('partido', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('ts', models.BigIntegerField()),
                ('hash_voto', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['distrito'], name='dni_checker_distrit_934e55_idx'), models.Index(fields=['dni'], name='dni_checker_dni_d6e95b_idx')],
            },
        ),
    ]
